### ISSUE TITLE
Change organization of 'Data supporting SNP' page

### ISSUE THREAD

**Issue by euriehong** [hitz/RegulomeDB#18]
This is based on recent changes to the Manually curated data.  How data should be grouped on the page. 
# Protein binding sites

Include the following data rows:
    TF_(cell type)_(TF)[_(Condition)](method)_(cell type)_(TF)_PMID_MANUALTF
        sample: chr11   5248827 5248851 (reporter_gene_assay|electrophoretic_mobility_shift_assay)_(K562)_(DLX4)_PMID10908341_MANUALTF
        sample: chrX    146992810   146993118   (chromatin_immunoprecipitation_experiment)_(lymphocyte)_(MAX|USF1|USF2|CREB_binding_protein)_PMID15175277|PMID16500891_MANUALTF

Columns:
    \* Method
            TF = ChIP-seq
            Manual = can be parsed 'method' from name.  Multiples separated by "|" - can be kept together
    \* Location
    \* Bound protein
            for both, parsed (TF) from name.  Also can include POL2 and histone deactetylases, not exclusively TF.  Multiples separated by "|" - can be kept together
    \* Cell type
            for both, parsed (cell type) from name.
    \* Additional info
            for TF, parse (condition)
    \* Reference
            NCP000 = ENCODE if no paper
            MANUAL = PMID# (no need to have PMID preface).  Multiples separated by "|".
# Inferred binding sites

Include the following data rows:
    FP_(cell type)_(TF)
    (method)_(cell type)_(TF)_PMID_MANUAL
        sample: chrX    146993352       146993374       (DNase_I_footprint)_(SK-N-SH)_(AP-2-alpha)_PMID10612627_MANUAL
        chrX    146993338       146993344       (DMS_footprinting)_(fibroblast)_()_PMID9328468_MANUAL

Columns:
    \* Method
        FP = Footprinting
        Manual = can be parsed 'method' from name.  
    \* Location
    \* Motif
            for both, parsed from (TF)
    \* Cell type
            parsed (cell type)
    \* Reference
        FP: PMID
        Manual: PMID# (no need to have PMID preface)
# Motifs

Include the following data rows:
    PWM_(TF)
    MOTIF_(TF)_PMID_MANUAL
        sample: chr11   5248401 5248402 MOTIF_(CACCC_box)_PMID10606872|PMID15352994_MANUAL  

Columns:
    \* Location
    \* Motif
        for both, parse TF
    \* Additional info
            for PWM, add LOGO?
    \* Reference
            PWM: Is there a reference?
        Manual: PMID# (no need to have PMID preface).  Multiples separated by "|".
# DNase hypersensitive sites

Include the following data rows:
    DNase_(cell type)[_(Condition)]

Columns:
    \* Method
            DNase = DNase hyersensitivity
    \* Location
    \* Cell type
            parsed from name
    \* Additional info
            parse (condition)
    \* Reference
            PMID?
# Single nucleotides

Include the following data rows:
    VAL_(cell type)_(TF)_(additional info)
    eQTL_(cell type)_(gene target)
    SNV_(cell type)_(gene target)_(additional info)_PMID_MANUAL
        sample: chr11   5248356 5248357 SNV_()_()_(identified_in_a_Algerian_patient_with_beta-thalassaemia)_PMID18081706_MANUAL
        sample: chr11   5248387 5248388 SNV_(HeLa)_(HBB)_(decreased_gene_expression)_PMID2018842__MANUAL

Columns:
    \* Method
                VAL = Validated SNP
                eQTL = eQTL
                MANUAL = leave blank
    \* Location
    \* Affected gene
                for VAL, parse (TF)
                for eQTL, parse (gene target)
        for SNV, parse (gene target)
    \* Cell type
                for all, parsed from (cell type)
    \* Additional Info
                for VAL, parse (additional info)
        for manual = parse (additional info)
    \* Reference
            for all, PMID, no need to have PMID preface
# Other

Include the following data rows:
    (method)_(cell type)_(annotation)_PMID_MANUAL
        sample: chr11   5255569 5255570 ()_()_(canonical_five_prime_splice_site)_PMID3401592_MANUAL
        sample: chr11   5276059 5276061 (RNA_protection_assay|RT-PCR_transcription_analysis)_(K562)_(major_TSS)_PMID6701091_MANUAL
        sample: chrX    146993279       146993280       ()_()_(intergenic_region)_PMID10799273_MANUAL
Columns:
    \* Method
            parse method
    \* Location
    \* Cell type
            parsed from name
    \* Annotation
            parse (annotation)
    \* Reference
            PMID, no need to have PMID preface

**Comment by euriehong** [comment]
Thoughts for the future.   All data should be tagged with 'annotation_type' (HTP datasets, computational predictions, manually curated data) as well as an experimental method that is based on an ontology.  Experimental methods can be grouped together by slimming the ontology.

**Comment by aboyle** [comment]
I've implemented all of these (from the first comment) now.

**Comment by hitz** [comment]
there is a further reorganization to be added in beta release due to DB reworking.

**Comment by hitz** [comment]
done, I think, although we are still taking about sorting/filtering
