### ISSUE TITLE
Need new map image for 'data supporting SNP' page

### ISSUE THREAD

**Issue by euriehong** [hitz/RegulomeDB#19]
Issues with current image: too zoomed out, cannot locate where your coordinate of interest is on the page.

I will look to see if ENSEMBL has a different image option that can provide maybe 15-20K region as well as indicate where on the map you are.

Also, this map should link to ENSEMBL.  Will include link when I find new source of image.

**Comment by aboyle** [comment]
I've got a link to handle this. After meeting with the Mike's the idea is to include gene information from GENCODE v7 and dynamically picking the region from ENSEMBL by either just showing the gene that the feature is near or showing to just past the nearest upstream and downstream gene.

**Comment by euriehong** [comment]
I agree in principle that we need to add gene coordinate information to the database.  But given the two week time frame and other priorities of the website (getting large files to work, including the ability to download results, getting manually curated data visible on the site, etc) it may not be feasible to include this as well.

**Comment by euriehong** [comment]
After corresponding with Ensembl folks, no ideal solution for easy map changes.  You could use this URL to generate the map with a defined set of coordinates (like take the SNP +/- 10kb):

http://uswest.ensembl.org/Homo_sapiens/Component/Location/Web/Region?r=11:5245957-5265957;export=png

But the tracks are not configurable and you cannot mark a position with a red line.

**Comment by aboyle** [comment]
I've added this as well as a link out to Ensembl by clicking the image.

On Fri, Nov 11, 2011 at 10:16 AM, euriehong
reply@reply.github.com
wrote:

**Comment by hitz** [comment]
Alan managed to hack in a nice UCSC browser image, this will go in the beta release

**Comment by aboyle** [comment]
This was done using a link demonstrated in the UCSC javascript. The link formatting is below:

http://genome.cse.ucsc.edu/cgi-bin/hgRenderTracks?hgsid=245174063&mrna=hide&textSize=12&intronEst=hide&knownGene=hide&multiz46way=hide&leftLabels=off&snp132Common=hide&rmsk=dense&snp135Common=hide&pix=740&position=chr2:1100-12200

The hgsid=245174063 will actually hide everything that the person may have already added to the browser track views. If we leave this out then the image will grab those tracks as well as they are stored in the browser session.

We still need to find a way to draw a red line down the middle.

**Comment by hitz** [comment]
> We still need to find a way to draw a red line down the middle.

http://keith-wood.name/svg.html
SVG jquery plugin.  See "Examples"  pull down images - they draw an image on another image.  A red line would be pretty easy I think.

**Comment by hitz** [comment]
done, ready for beta release
