### ISSUE TITLE
Make SNP Results sortable

### ISSUE THREAD

**Issue by aboyle** [hitz/RegulomeDB#23]
Some of the results return a large number of hits so sorting would be helpful. Particularly in the case of Histone modifications where we would like to be able to sort by cell type or histone mark.

**Comment by hitz** [comment]
I think we just have to remove the bSort: 0 from the data tables parameters in SNP.pm.   If we wanted to get fancy we could enable it if the number of rows in table was > 10 or something.  Filtering is also trivial to enable.

**Comment by hitz** [comment]
I think we need to talk more about what kind of filtering we should enable on which table/colums

**Comment by aboyle** [comment]
I'm not sure that the search feature is needed in conjunction with the sort feature. It looks a little clunky. If we keep it maybe move to the right of the top row instead of creating its own row.

**Comment by hitz** [comment]
might be able to look at this in a couple weeks.  One way the "search" type thing is often implemented is as a filter on EACH column.  Takes up more real estate but can be clearer.

For an example see: http://www.yeastgenome.org/cgi-bin/interactions.pl?dbid=S000006161

**Comment by hitz** [comment]
moved the Search box to the right and renamed it Filter.  Let me know if we should try to implement more complex filtering (column1 = x, column2 =y ...)

**Comment by hitz** [comment]
oh right of the TOP row... hmm.  I will try

**Comment by hitz** [comment]
boy that took a while.  I think it's very close now.  Maybe the text could be twiddled up and down some.

**Comment by hitz** [comment]
Well, no one commented so I guess it doen.
